// frontend/src/pages/TermsOfServicePage.jsx
import { Link } from 'react-router-dom';
import { HiDocumentText, HiArrowLeft } from 'react-icons/hi';

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="text-xl font-bold text-primary-theme mb-4 pb-2 border-b border-theme">
      {title}
    </h2>
    <div className="leading-relaxed space-y-3 text-muted-theme">{children}</div>
  </div>
);

const TermsOfServicePage = () => {
  return (
    <div className="min-h-screen">
      {/* Hero Header */}
      <div className="relative py-16 px-4 overflow-hidden border-b border-theme">
        <div className="absolute inset-0 bg-gradient-to-br from-accent-700/10 via-transparent to-transparent" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-48 bg-accent-700/10 rounded-full blur-3xl" />
        <div className="relative max-w-3xl mx-auto text-center">
          <div className="inline-flex items-center space-x-2 bg-accent-700/10 border border-accent-700/20 rounded-full px-4 py-2 mb-6">
            <HiDocumentText className="text-accent-400 h-4 w-4" />
            <span className="text-accent-300 text-sm font-medium">Legal Agreement</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4 text-primary-theme">Terms of Service</h1>
          <p className="text-lg text-muted-theme">
            Last updated: <span className="text-primary-theme font-medium">July 2025</span>
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-12">
        <Link
          to="/"
          className="inline-flex items-center space-x-2 text-slate-400 hover:text-white text-sm mb-10 transition-colors"
        >
          <HiArrowLeft className="h-4 w-4" />
          <span>Back to Home</span>
        </Link>

        <div
          className="rounded-2xl p-8 md:p-10 border"
          style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border)' }}
        >

          <Section title="1. Agreement to Terms">
            <p>
              By accessing or using <strong className="text-white">PolicySimplifier</strong> ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you do not have permission to access the Service.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              PolicySimplifier is a Software-as-a-Service (SaaS) application that uses Optical Character Recognition (OCR) and Artificial Intelligence (AI) to parse, analyse, and simplify insurance policy documents. The Service provides summaries for informational purposes only.
            </p>
            <p className="font-medium text-yellow-400 bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-3">
              ⚠️ Disclaimer: PolicySimplifier is NOT a licensed insurance advisor, broker, or legal consultant. Summaries generated by the AI are for informational reference only and do not constitute professional insurance, financial, or legal advice. Always consult a qualified advisor before making insurance decisions.
            </p>
          </Section>

          <Section title="3. Account Registration">
            <p>To use the Service, you must:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Be at least 18 years of age.</li>
              <li>Provide accurate and complete registration information (name and email address).</li>
              <li>Maintain the security of your account password. You are responsible for all activity under your account.</li>
              <li>Notify us immediately of any unauthorized account access at <span className="text-primary-400">support@policysimplifier.in</span>.</li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use Policy">
            <p>You agree NOT to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Upload documents that contain fraudulent, forged, or stolen insurance information.</li>
              <li>Attempt to reverse-engineer, scrape, or programmatically extract data from the application without authorization.</li>
              <li>Circumvent subscription limits or billing mechanisms (e.g., creating multiple free accounts to bypass the 1 upload/month limit).</li>
              <li>Upload content that is illegal, harmful, or violates any applicable local or international laws.</li>
              <li>Use the service for resale or redistribution without a valid Agent Pro or Enterprise license.</li>
            </ul>
          </Section>

          <Section title="5. Subscription Plans & Billing">
            <p>
              PolicySimplifier offers Free and paid subscription plans as outlined on our pricing page. By subscribing to a paid plan:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>You authorize us to charge your chosen payment method on a recurring monthly or one-time basis.</li>
              <li>Payments are processed securely by Razorpay (India) or Stripe (Global). We do not store card details.</li>
              <li>Subscription fees are <strong className="text-white">non-refundable</strong> unless required by applicable consumer protection law.</li>
              <li>We reserve the right to change pricing with <strong className="text-white">30 days' advance notice</strong> via email.</li>
              <li>Failure to pay will result in automatic downgrade to the Free tier.</li>
            </ul>
          </Section>

          <Section title="6. Intellectual Property">
            <p>
              The Service, including its UI design, codebase, AI prompt engineering, and brand assets, are the exclusive intellectual property of PolicySimplifier and protected by applicable copyright laws.
            </p>
            <p>
              Documents you upload remain <strong className="text-white">your property</strong>. By uploading, you grant us a limited, non-exclusive, royalty-free licence to process your documents solely for the purpose of generating your requested summary.
            </p>
          </Section>

          <Section title="7. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, PolicySimplifier shall not be liable for:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Any inaccuracies in AI-generated policy summaries.</li>
              <li>Insurance decisions made based on the Service's output.</li>
              <li>Any indirect, incidental, or consequential damages arising from use of the Service.</li>
              <li>Loss of data resulting from hardware failures, third-party outages, or Force Majeure events.</li>
            </ul>
            <p>
              Our total liability in any event is limited to the amount you paid us in the <strong className="text-white">3 months preceding the claim</strong>.
            </p>
          </Section>

          <Section title="8. Termination">
            <p>
              We reserve the right to suspend or terminate accounts that violate these Terms without prior notice. You may delete your account at any time from your profile settings, which will purge all associated data within 30 days.
            </p>
          </Section>

          <Section title="9. Changes to Terms">
            <p>
              We may update these Terms periodically. When we do, we will revise the "Last updated" date at the top of this page and notify active subscribers by email. Continued use of the Service after changes constitutes your acceptance of the new Terms.
            </p>
          </Section>

          <Section title="10. Governing Law">
            <p>
              These Terms shall be governed by and construed in accordance with the laws of <strong className="text-white">India</strong>. Any disputes shall be subject to the exclusive jurisdiction of courts in India.
            </p>
          </Section>

          <Section title="11. Contact Us">
            <p>
              If you have any questions about these Terms, please contact:
            </p>
            <div className="mt-3 p-4 rounded-xl border" style={{ backgroundColor: 'var(--bg-card-2)', borderColor: 'var(--border)' }}>
              <p className="font-medium text-primary-theme">PolicySimplifier</p>
              <p>Email: <span className="text-primary-400">legal@policysimplifier.in</span></p>
            </div>
          </Section>

        </div>

        <div className="mt-6 text-center text-slate-500 text-sm">
          Also read our{' '}
          <Link to="/privacy" className="text-primary-400 hover:text-primary-300 transition-colors">
            Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
